import { LegalScreen, LegalSection } from "@/components/legal-screen";

export default function PrivacyScreen() {
  return (
    <LegalScreen title="Privacy Policy" updated="9 September 2026">
      <LegalSection title="1. What this policy covers">This Privacy Policy explains how Briefly handles information when you use the Briefly app, website, account, subscriptions, saved stories, and related features.</LegalSection>
      <LegalSection title="2. Information we may process">Depending on the features you use, Briefly may process account information such as your email address and account identifier, authentication data, subscription or entitlement status, saved-story identifiers, language and appearance preferences, feature usage, diagnostic information, and content you explicitly ask Briefly to process.</LegalSection>
      <LegalSection title="3. Authentication and account providers">Briefly uses Supabase for supported authentication and account infrastructure. If you sign in with Apple, Google, or another identity provider, that provider may process information under its own privacy terms.</LegalSection>
      <LegalSection title="4. Payments and subscriptions">Briefly does not need to store your full payment-card details. Subscription purchases may be processed by Apple, Google, Stripe, RevenueCat, or another supported payment provider. Briefly may receive identifiers, entitlement state, billing status, plan information, and related metadata needed to provide and restore paid features.</LegalSection>
      <LegalSection title="5. News, AI, and processing services">Briefly may send relevant text, prompts, article information, or other content to service providers used for hosting, search, translation, text generation, audio generation, analytics, or other product functions. We aim to limit this to information reasonably necessary to provide the requested feature.</LegalSection>
      <LegalSection title="6. How information is used">We use information to operate Briefly, authenticate users, provide saved and paid features, restore purchases, generate requested content, maintain security, diagnose problems, prevent abuse, improve reliability, and comply with legal obligations.</LegalSection>
      <LegalSection title="7. Sharing">We may share information with processors and infrastructure providers that help operate Briefly, with payment and identity providers when needed for their services, where required by law, or as part of a legitimate business transfer.</LegalSection>
      <LegalSection title="8. Retention">We retain information only for as long as reasonably needed for the purposes described here, subject to legal, security, fraud-prevention, accounting, backup, and dispute-resolution requirements. Some information may remain temporarily in backups or provider systems after deletion.</LegalSection>
      <LegalSection title="9. Account deletion">You can request deletion directly from Briefly's in-app Account screen. Account deletion removes the Briefly identity and associated Briefly profile data handled by the deletion service. Some records may be retained where required by law or needed for legitimate security, fraud-prevention, billing, or dispute purposes.</LegalSection>
      <LegalSection title="10. Security">We use reasonable technical and organisational measures designed to protect information, but no system or transmission method can be guaranteed completely secure.</LegalSection>
      <LegalSection title="11. International processing">Briefly and its service providers may process information in countries other than your own. Where required, appropriate safeguards are used for international transfers.</LegalSection>
      <LegalSection title="12. Your rights">Depending on where you live, you may have rights to access, correct, delete, restrict, object to, or receive a copy of certain personal information. You can also delete your Briefly account in-app and contact us for privacy requests.</LegalSection>
      <LegalSection title="13. Children">Briefly is not directed to children under the minimum age required to consent to digital services in their jurisdiction. If we learn that personal information was collected from a child contrary to applicable law, we will take appropriate steps.</LegalSection>
      <LegalSection title="14. Changes and contact">We may update this Privacy Policy as Briefly changes. Material changes will be communicated as required by law. Privacy questions can be sent through Contact & Support in Briefly.</LegalSection>
    </LegalScreen>
  );
}
